# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.5
    restart: unless-stopped
    # network_mode: ${NETWORK_MODE}
    command: 
      --innodb-buffer-pool-size=512M 
      --query-cache-size=64M 
      --tmp-table-size=64M 
      --max-heap-table-size=64M
      --ssl-ca=/etc/certs/root-ca.pem
      --ssl-cert=/etc/certs/server-cert.pem
      --ssl-key=/etc/certs/server-key.pem
      --default_authentication_plugin=mysql_native_password
      --bind-address=0.0.0.0
      --require_secure_transport=ON
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_ROOT_HOST: "%"
    volumes:
      - ${DB_LOCATION}:/var/lib/mysql
      - type: bind
        source: ${CERT_LOCATION}
        target: /etc/certs/
        read_only: true
    ports:
      - 3306:3306

  adminer:
    image: adminer:4.8.1-standalone
    # network_mode: ${NETWORK_MODE}
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_SSL_KEY: '/certs/client-key.pem'
      DB_SSL_CERT: '/certs/client-cert.pem'
      DB_SSL_CA: '/certs/root-ca.pem'
      ADMINER_DEFAULT_SERVER: db
    volumes:
      - ./plugins/login-ssl.php:/var/www/html/plugins-enabled/login-ssl.php
      - ${CERT_LOCATION}/client-key.pem:/certs/client-key.pem
      - ${CERT_LOCATION}/client-cert.pem:/certs/client-cert.pem
      - ${CERT_LOCATION}/root-ca.pem:/certs/root-ca.pem